### PR TITLE
Fixed minor formatting bugs

### LINKED ISSUE #10: Fix indent issue with the first line of a code block

### PR DESCRIPTION
**Pull request by BenjammingKirby**
### READY TO TEST AND MERGE 👍🏻
- **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix, feature
- **What is the current behavior?** (You can also link to an open issue here)

1. [botched indentation](https://github.com/tatupesonen/formatbot/issues/10) if the original content has excess indentation
2. For the pastecord code, this doesn't add comments/adds it in an unexpected way for multi line codeblock content
- **What is the new behavior (if this is a feature change)?**
Fixes the issues mentioned above
~~adds option to have only the codeblock content (not yet implemented)~~ ( Pushed to a later commit )
- **Other information**:
fixes #10

### CODE REVIEW

File: src/lib/util/FormatMessage.ts [hunk 1]
```diff
@@ -1,20 +1,20 @@
...
-} from '../formatters/FormatterMappings';
+import { languageMappings } from '../formatters/FormatterMappings';
 import { UploadToPastecord } from '../infra/external/pastecordintegration';
 import { reformat } from './reformatter';
 import { asyncStringReplacer, commentify } from './utils';
 
-export const formatMessage = async (message: Message) => {
+export const formatMessage = async (
+  message: Message,
+  _onlyCodeBlocks?: boolean
```
Comment (BenjammingKirby) [inline src/lib/util/FormatMessage.ts:9]: Currently in dev, this is what the onlyCodeBlocks option will use

**Comment by tatupesonen** [comment]
Thanks for the PR. Do you mind changing the base branch to be dev?

File: src/lib/util/FormatMessage.ts [hunk 2]
```diff
@@ -1,20 +1,20 @@
...
+) => {
   const content = message.content;
   // The first language key found, it'll be used for the pastecord file and all the comments on the file
-  let firstLanguageKey: string | undefined;
+  let firstLanguageKey: string | undefined = content.match(
+    new RegExp(`\`\`\`(${Object.keys(languageMappings).join('|')})\n`, 'm')
```
Comment (BenjammingKirby) [inline src/lib/util/FormatMessage.ts:14]: Instead of assigning it later on, this should be assigned at the very beginning since we want code blocks that come before a valid code block be commented judging by this

File: src/lib/util/FormatMessage.ts [hunk 3]
```diff
@@ -1,20 +1,20 @@
...
+  )?.[1];
   // The message's content with the code blocks and their contents removed
   let contentWithoutCode = content;
-  // The content that'll be uploaded to pastecord
-  let pastecordCode = content;
```
Comment (BenjammingKirby) [inline src/lib/util/FormatMessage.ts:17]: pastecordCode originally was meant to be the code that we send as the "original code", since that feature was discarded, there's no use for this at all

File: src/lib/util/FormatMessage.ts [hunk 4]
```diff
@@ -32,26 +32,38 @@ export const formatMessage = async (message: Message) => {
...
+          // returning match itself means nothing will be changed
           return match;
         }
         // For empty codeblocks, remove the content
         unformattableCodeBlockCounter++;
+        // Returning '' will completely remove the empty code block
         return '';
       }
-      // If firstLanguage is undefined and language is a valid languagekey, it sets the value
-      if (!firstLanguageKey && languageNameMappings[language])
```
Comment (BenjammingKirby) [inline src/lib/util/FormatMessage.ts:42]: as mentioned above, now we'll assign it on declaring firstLanguageKey instead of going through all of it

File: src/lib/util/FormatMessage.ts [hunk 5]
```diff
@@ -73,7 +85,7 @@ export const formatMessage = async (message: Message) => {
         );
       }
       //Replace the string's code with the formatted code inside a code block
-      return match.replace(theCode, formattedCode);
+      return match.replace(codeContent, '\n' + formattedCode.trim() + '\n');
```
Comment (BenjammingKirby) [inline src/lib/util/FormatMessage.ts:88]: This was causing the indentation issue
it used to attempt to replace the codeContent.trim() prior to this, now it changes the entire code block content, to add further context: \`\`\`codeContent\`\`\` that's what codeContent is

File: src/lib/util/FormatMessage.ts (hunk 1 above)
Comment (BenjammingKirby) [inline src/lib/util/FormatMessage.ts:9]: Currently in dev, this is what the onlyCodeBlocks option will use

**Review by tatupesonen — APPROVED** [review]
Looks good
